# Generated by Django 6.0.7 on 2026-07-21 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentoringRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_semester', models.CharField(blank=True, max_length=20)),
                ('improvement_status', models.CharField(blank=True, choices=[('IMPROVING', 'Improving'), ('STABLE', 'Stable'), ('NEEDS_ATTENTION', 'Needs Attention')], max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('academic_challenges', models.TextField(blank=True)),
                ('personal_issues', models.TextField(blank=True)),
                ('emotional_psychological_concerns', models.TextField(blank=True)),
                ('career_counseling', models.TextField(blank=True)),
                ('examination_stress', models.TextField(blank=True)),
                ('logistical_challenges', models.TextField(blank=True)),
                ('short_term_goals', models.TextField(blank=True)),
                ('long_term_goals', models.TextField(blank=True)),
                ('personal_development_goals', models.TextField(blank=True)),
                ('mentor_comments', models.TextField(blank=True)),
                ('student_reflection', models.TextField(blank=True)),
                ('next_meeting_date', models.DateField(blank=True, null=True)),
                ('next_meeting_focus', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='mentoring_pdfs/')),
                ('is_finalized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentoring_record', to='meetings.meeting')),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentoring_records', to='accounts.menteeprofile')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentoring_records', to='accounts.mentorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_description', models.CharField(max_length=255)),
                ('assigned_to', models.CharField(max_length=120)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=15)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='mentoring.mentoringrecord')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=120)),
                ('attendance_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('performance_remarks', models.CharField(blank=True, max_length=255)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='mentoring.mentoringrecord')),
            ],
        ),
    ]
